---
title: "The reticulate package"
subtitle: Integration of Python into R projects
output:
  html_document: default
  runtime: shiny
---

***

### Setup

```{r setup}
library(reticulate)
readr::write_csv(nycflights13::flights,path = "flights.csv")


#print(reticulate::py_config())
#print(capture.output(reticulate::py_config()))
```

```{r app}
# update apps set app_mode = 2 where appid = 31;
library(shiny)
library(stringr)
ui <- fluidPage(
   
   # Application title
   titlePanel("Shell App!"),
   
   sidebarLayout(
     sidebarPanel = NULL,
      mainPanel = mainPanel(
         "Enjoy a shell where you ought not have one!"
         , textInput('command', label='Enter Command')
         , actionButton('execute', label='Run!')
         , textInput('envir', label='Enter name=value pairs to set environment variables (quoting is weird)')
         , verbatimTextOutput("text")
      )
   )
)

server <- function(input, output) {
   
   output$text <- eventReactive(
     input$execute, {
       
       print('Running event reactive')
       first_space <- str_locate(input$command,' ')[[1,'start']]
       if (!is.na(first_space)) {
         command <- str_sub(input$command,1,first_space-1)
         args <- str_sub(input$command,first_space+1)
       } else {
         command <- input$command
         args <- character()
       }
       envir <- input$envir
       print(sprintf('Command: %s',command))
       print(sprintf('Args: %s',args))
       print(sprintf('Env: %s', envir))
       returnval <- system2(command=command, args=args
                           , stdout=TRUE
                           , stderr=TRUE
                           , env = envir)
       
       return(paste(returnval,collapse='\n'))
     }
   )
}

# Run the application 
shinyApp(ui = ui, server = server)
```
***

# From Python to R


### Use Python to manipulate data


### Use R to visualize Pandas DataFrame

```{r, fig.width=7, fig.height=3}
#library(ggplot2)
#ggplot(py$flights, aes(carrier, arr_delay)) + geom_point() + geom_jitter()
```

***

# From R to Python

### Use R to read and manipulate data

```{r, message=FALSE}
#library(readr)
#library(dplyr)
#flights <- read_csv("flights.csv") %>%
#  filter(dest == "ORD") %>%
#  select(carrier, dep_delay, arr_delay) %>%
#  na.omit()
```

### Use Python to print R dataframe


***

See the [reticulate website](https://rstudio.github.io/reticulate/index.html) for details.

